name: Deploy on push
on: push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: sandrax0.ftp.tools
        username: sandrax0_site
        password: ${{ secrets.ftp_password }}
